### PR TITLE
Fix for the download bug

### PR DESCRIPTION
**Pull request by Mageti**
Now, if not given the full path (/tmp/foo.tar.gz), the `get_url` task will use a UUID for the filename (/tmp/ff77ff24-1264-11e7-835e-8d427dffb60b).
This leaded to the `unarchive` task to fail, since it uses the full path.
This commit fixes the bug.

### CODE REVIEW

**Comment by jnogol** [comment]
Hi @Mageti,

I just tried with Ansible 2.3 and 2.4 and didn't run into any issues. Can you please tell us your OS and Ansible version?

**Comment by Mageti** [comment]
Hello,
I use latest ansible:
```$ ansible --version
ansible 2.4.2.0
  config file = /home/<USER>/code/ha-at-scale-hipchat/ansible.cfg
  configured module search path = ['/home/<USER>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<USER>/code/ha-at-scale-hipchat/venv/lib/python3.5/site-packages/ansible
  executable location = /home/<USER>/code/ha-at-scale-hipchat/venv/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

The requirements.yml:
```
- src: idealista.prometheus_redis_exporter-role
  name: g_role_prometheus_redis_exporter
```
The playbook:
```
- hosts: hc-redis
  remote_user: ubuntu
  become: true
  roles:
    - g_role_redis
    - g_role_prometheus_redis_exporter
  tags: redis
```

Here is the relevant part of the ansible log running with `-vvv`:
```
TASK [g_role_prometheus_redis_exporter : REDIS_EXPORTER | Download package] *************************************************************************************************************
task path: /home/<USER>/.ansible/roles/g_role_prometheus_redis_exporter/tasks/install.yml:32
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: redis_exporter_force_reinstall or redis_exporter_check|failed or "Redis
Metrics Exporter v{{ redis_exporter_version }}" not in redis_exporter_check.stderr

Using module file /home/<USER>/code/ha-at-scale-hipchat/venv/lib/python3.5/site-packages/ansible/modules/net_tools/basics/get_url.py
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.123.11> (0, b'/home/ubuntu\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853 `" && echo ansible-tmp-1514560883.5791724-98295200923853="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853 `" ) && sleep 0'"'"''
<192.168.123.11> (0, b'ansible-tmp-1514560883.5791724-98295200923853=/home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853\n', b'')
<192.168.123.11> PUT /tmp/tmphoi68tp7 TO /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853/get_url.py
<192.168.123.11> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 '[192.168.123.11]'
<192.168.123.11> (0, b'sftp> put /tmp/tmphoi68tp7 /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853/get_url.py\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853/ /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853/get_url.py && sleep 0'"'"''
<192.168.123.11> (0, b'', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 -tt 192.168.123.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-oeswxmupchaobwoxruggmeemsttikvbd; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853/get_url.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1514560883.5791724-98295200923853/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<192.168.123.11> (0, b'sudo: unable to resolve host hipchat-redis-01: Connection timed out\r\n\r\n{"group": "root", "url": "https://github.com/oliver006/redis_exporter/releases/download/v0.10.9/redis_exporter-v0.10.9.linux-amd64.tar.gz", "uid": 0, "invocation": {"module_args": {"serole": null, "unsafe_writes": null, "client_cert": null, "timeout": 10, "seuser": null, "selevel": null, "dest": "/tmp", "owner": null, "directory_mode": null, "regexp": null, "force_basic_auth": false, "headers": null, "delimiter": null, "backup": null, "url_username": null, "url_password": null, "group": null, "force": false, "url": "https://github.com/oliver006/redis_exporter/releases/download/v0.10.9/redis_exporter-v0.10.9.linux-amd64.tar.gz", "http_agent": "ansible-httpget", "checksum": "", "tmp_dest": null, "use_proxy": true, "remote_src": null, "attributes": null, "validate_certs": true, "src": null, "path": "/tmp/ff77ff24-1264-11e7-835e-8d427dffb60b", "setype": null, "client_key": null, "mode": null, "sha256sum": "", "follow": false, "content": null}}, "gid": 0, "mode": "0644", "status_code": 200, "dest": "/tmp/ff77ff24-1264-11e7-835e-8d427dffb60b", "owner": "root", "checksum_src": "edb076efe8b703e5eaadea55c8e4eb6f08129bb1", "src": "/tmp/tmptwpb1thm", "size": 2592380, "checksum_dest": "edb076efe8b703e5eaadea55c8e4eb6f08129bb1", "changed": false, "msg": "OK (2592380 bytes)", "md5sum": "89ea9c1a798d8bbc3aad666d765d3175", "state": "file"}\r\n', b'Shared connection to 192.168.123.11 closed.\r\n')
ok: [hipchat-redis-01.stg.nova] => {
    "changed": false,
    "checksum_dest": "edb076efe8b703e5eaadea55c8e4eb6f08129bb1",
    "checksum_src": "edb076efe8b703e5eaadea55c8e4eb6f08129bb1",
    "dest": "/tmp/ff77ff24-1264-11e7-835e-8d427dffb60b",
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "path": "/tmp/ff77ff24-1264-11e7-835e-8d427dffb60b",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://github.com/oliver006/redis_exporter/releases/download/v0.10.9/redis_exporter-v0.10.9.linux-amd64.tar.gz",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "md5sum": "89ea9c1a798d8bbc3aad666d765d3175",
    "mode": "0644",
    "msg": "OK (2592380 bytes)",
    "owner": "root",
    "size": 2592380,
    "src": "/tmp/tmptwpb1thm",
    "state": "file",
    "status_code": 200,
    "uid": 0,
    "url": "https://github.com/oliver006/redis_exporter/releases/download/v0.10.9/redis_exporter-v0.10.9.linux-amd64.tar.gz"
}

TASK [g_role_prometheus_redis_exporter : REDIS_EXPORTER | Extract downloaded package] ***************************************************************************************************
task path: /home/<USER>/.ansible/roles/g_role_prometheus_redis_exporter/tasks/install.yml:38
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: redis_exporter_force_reinstall or redis_exporter_check|failed or "Redis
Metrics Exporter v{{ redis_exporter_version }}" not in redis_exporter_check.stderr

<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.123.11> (0, b'/home/ubuntu\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.1530945-187301068543178 `" && echo ansible-tmp-1514560890.1530945-187301068543178="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.1530945-187301068543178 `" ) && sleep 0'"'"''
<192.168.123.11> (0, b'ansible-tmp-1514560890.1530945-187301068543178=/home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.1530945-187301068543178\n', b'')
Using module file /home/<USER>/code/ha-at-scale-hipchat/venv/lib/python3.5/site-packages/ansible/modules/files/stat.py
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.123.11> (0, b'/home/ubuntu\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936 `" && echo ansible-tmp-1514560890.217021-144783975597936="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936 `" ) && sleep 0'"'"''
<192.168.123.11> (0, b'ansible-tmp-1514560890.217021-144783975597936=/home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936\n', b'')
<192.168.123.11> PUT /tmp/tmp8jw1bltz TO /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936/stat.py
<192.168.123.11> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 '[192.168.123.11]'
<192.168.123.11> (0, b'sftp> put /tmp/tmp8jw1bltz /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936/stat.py\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936/ /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936/stat.py && sleep 0'"'"''
<192.168.123.11> (0, b'', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 -tt 192.168.123.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qxmmnjxvfuwakjbvffpqnshvigiqwciw; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936/stat.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.217021-144783975597936/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<192.168.123.11> (0, b'sudo: unable to resolve host hipchat-redis-01: Connection timed out\r\n\r\n{"changed": false, "stat": {"block_size": 4096, "xgrp": true, "version": "18446744073095839986", "roth": true, "charset": "binary", "writeable": true, "ctime": 1514560900.5576143, "wusr": true, "wgrp": true, "mtime": 1514560900.5576143, "exists": true, "path": "/tmp", "issock": false, "nlink": 10, "rgrp": true, "woth": true, "xusr": true, "pw_name": "root", "gr_name": "root", "ischr": false, "inode": 4454, "xoth": true, "mode": "1777", "executable": true, "blocks": 8, "uid": 0, "size": 4096, "islnk": false, "mimetype": "inode/directory", "attributes": ["extents"], "isreg": false, "gid": 0, "rusr": true, "isgid": false, "isuid": false, "readable": true, "device_type": 0, "isfifo": false, "isdir": true, "dev": 64769, "atime": 1514560829.6486723, "attr_flags": "e", "isblk": false}, "invocation": {"module_args": {"get_checksum": true, "follow": true, "checksum_algo": "sha1", "path": "/tmp", "get_mime": true, "checksum_algorithm": "sha1", "get_md5": false, "get_attributes": true}}}\r\n', b'Shared connection to 192.168.123.11 closed.\r\n')
Using module file /home/<USER>/code/ha-at-scale-hipchat/venv/lib/python3.5/site-packages/ansible/modules/files/unarchive.py
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.123.11> (0, b'/home/ubuntu\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814 `" && echo ansible-tmp-1514560890.7823129-152904414293814="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814 `" ) && sleep 0'"'"''
<192.168.123.11> (0, b'ansible-tmp-1514560890.7823129-152904414293814=/home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814\n', b'')
<192.168.123.11> PUT /tmp/tmpjcq2u5ek TO /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814/unarchive.py
<192.168.123.11> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 '[192.168.123.11]'
<192.168.123.11> (0, b'sftp> put /tmp/tmpjcq2u5ek /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814/unarchive.py\n', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814/ /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814/unarchive.py && sleep 0'"'"''
<192.168.123.11> (0, b'', b'')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 -tt 192.168.123.11 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-iklqqcsmfnfqwwpvgnhjrdsbwnveydph; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814/unarchive.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.7823129-152904414293814/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<192.168.123.11> (0, b'sudo: unable to resolve host hipchat-redis-01: Connection timed out\r\n\r\n{"msg": "Source \'/tmp/redis_exporter-v0.10.9.linux-amd64.tar.gz\' does not exist", "invocation": {"module_args": {"backup": null, "validate_certs": true, "regexp": null, "owner": null, "mode": null, "creates": null, "content": null, "unsafe_writes": null, "selevel": null, "dest": "/tmp", "original_basename": "redis_exporter-v0.10.9.linux-amd64.tar.gz", "delimiter": null, "keep_newer": false, "group": null, "force": null, "exclude": [], "attributes": null, "extra_opts": [], "list_files": false, "src": "/tmp/redis_exporter-v0.10.9.linux-amd64.tar.gz", "setype": null, "seuser": null, "follow": false, "directory_mode": null, "serole": null, "remote_src": true}}, "failed": true}\r\n', b'Shared connection to 192.168.123.11 closed.\r\n')
<192.168.123.11> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<192.168.123.11> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/home/<USER>/.ansible/cp/223b457823 192.168.123.11 '/bin/sh -c '"'"'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1514560890.1530945-187301068543178/ > /dev/null 2>&1 && sleep 0'"'"''
<192.168.123.11> (0, b'', b'')
fatal: [hipchat-redis-01.stg.nova]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": "/tmp",
            "directory_mode": null,
            "exclude": [],
            "extra_opts": [],
            "follow": false,
            "force": null,
            "group": null,
            "keep_newer": false,
            "list_files": false,
            "mode": null,
            "original_basename": "redis_exporter-v0.10.9.linux-amd64.tar.gz",
            "owner": null,
            "regexp": null,
            "remote_src": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/tmp/redis_exporter-v0.10.9.linux-amd64.tar.gz",
            "unsafe_writes": null,
            "validate_certs": true
        }
    },
    "msg": "Source '/tmp/redis_exporter-v0.10.9.linux-amd64.tar.gz' does not exist"
}
	to retry, use: --limit @/home/<USER>/code/ha-at-scale-hipchat/deploy_hipchat.retry

PLAY RECAP ******************************************************************************************************************************************************************************
hipchat-redis-01.stg.nova  : ok=42   changed=1    unreachable=0    failed=1   
```

As you can see, the file `https://github.com/oliver006/redis_exporter/releases/download/v0.10.9/redis_exporter-v0.10.9.linux-amd64.tar.gz` is downloaded in `/tmp/ff77ff24-1264-11e7-835e-8d427dffb60b` where it should have been `/tmp/redis_exporter-v0.10.9.linux-amd64.tar.gz`.

This pull request just enforce the right behavior without changing anything else.

**Comment by jnogol** [comment]
Hi again,

Thanks for your quick reply and your contribution. Yes, it doesn't break anything and makes the role work in more scenarios, just was curious about the environment that makes it fail. Merging to our `develop` branch. I'll add a couple things more and release a new version.

Again, thank you for your contribution and your feedback.

Regards,
Jose

**Comment by Mageti** [comment]
:+1:

**Pull request merged**
